spring.application.name=${APP_NAME:payment-service}
server.port=${SERVER_PORT:8082}

# H2
spring.datasource.url=${DB_URL:jdbc:h2:mem:paymentdb}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# JPA
spring.jpa.database-platform=${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:create-drop}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

# H2 Console
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
spring.h2.console.path=${H2_CONSOLE_PATH:/h2-console}

# Order Service
order.service.url=${ORDER_SERVICE_URL:http://localhost:8083/api/orders}

# Logging
logging.level.com.shoppingcart=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=WARN
